name: Deploy Nuxt 3 App to GCP via gcloud

on:
  push:
    branches:
      - master  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '17'  # Ensure compatibility with Nuxt 3

    - name: Install dependencies
      run: npm install

    - name: Build the Nuxt app
      run: npm run generate

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Transfer files to GCP VM
      env:
        GCP_VM_NAME: ${{ secrets.GCP_VM_NAME }}
        GCP_VM_ZONE: ${{ secrets.GCP_VM_ZONE }}
        GCP_VM_PATH: ${{ secrets.GCP_VM_PATH }}
      run: |
        gcloud compute scp --recurse ./dist/* $GCP_VM_NAME:$GCP_VM_PATH --zone $GCP_VM_ZONE
